### ISSUE TITLE
app and service launch error on stateup carton

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/gulp#121]
ime="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;36;10mSTATEUP CARTON ASM1302247294959222784\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;37;10m==> pipeline [5]\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;32;10m  => step 0: generate-solo-json action\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;32;10m  => step 1: generate-solo-config action\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;32;10m  => step 2: clone-box action\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[0;33;10m  => step 2: clone-box action error - fatal error, couldn't locate the repository manager (github)\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;31;10m  => step 1: generate-solo-config action\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;31;10m  => step 0: generate-solo-json action\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=error msg="error on execute chefsolo pipeline for box unbuckles.megambox.com - fatal error, couldn't locate the repository manager (github)" 
time="2016-01-22T10:19:10+01:00" level=debug msg="\x1b[1;36;10munbuckles.megambox.com\x1b[0m in (\x1b[1;32;10m678.098µs\x1b[0m)\n\x1b[0;33;10m--- stateup box (unbuckles.megambox.com)\n--- kickofff chefsolo box (unbuckles.megambox.com)\n  generate solo json for box (unbuckles.megambox.com)  generate solo json for box (unbuckles.megambox.com) OK\n  generate solo config for box (unbuckles.megambox.com)\n  generate solo config for box (unbuckles.megambox.com) OK\n  clone repository for box (unbuckles.megambox.com)  clone repository for box failed.\nfatal error, couldn't locate the repository manager (github)\n\x1b[0m" 
time="2016-01-22T10:19:10+01:00" level=error msg="Unable to stateup box : fatal error, couldn't locate the repository manager (github)" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET --- stateup box (unbuckles.megambox.com) gulp shipwreck COM1302247294971805696}" 
ERR   19 (103.56.92.4:4150) IO error - EOF
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET --- kickofff chefsolo box (unbuckles.megambox.com) gulp shipwreck COM1302247294971805696}" 
ERR   20 (103.56.92.4:4150) IO error - EOF
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET   generate solo json for box (unbuckles.megambox.com) gulp shipwreck COM1302247294971805696}" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET   generate solo json for box (unbuckles.megambox.com) OK gulp shipwreck COM1302247294971805696}" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET   generate solo config for box (unbuckles.megambox.com) gulp shipwreck COM1302247294971805696}" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET   generate solo config for box (unbuckles.megambox.com) OK gulp shipwreck COM1302247294971805696}" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET   clone repository for box (unbuckles.megambox.com) gulp shipwreck COM1302247294971805696}" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET   clone repository for box failed. gulp shipwreck COM1302247294971805696}" 
time="2016-01-22T10:19:10+01:00" level=debug msg="unbuckles.megambox.com_log:{22 Jan 16 10:19 CET fatal error, couldn't locate the repository manager (github) gulp shipwreck COM1302247294971805696}"

**Comment by indykish** [comment]
@vijaykanthm28  Can you update the json for `ASM1302247294959222784`

**Comment by vijaykanthm28** [comment]
@indykish 
{"id":"ASM1302247294959222784","name":"unbuckles","json_claz":"Megam::Assembly","tosca_type":"tosca.app.java","inputs":[{"key":"domain","value":"megambox.com"},{"key":"sshkey","value":"kanth@megam.io_vs"},{"key":"provider","value":"one"},{"key":"cpu","value":"0.5"},{"key":"ram","value":"896"},{"key":"version","value":"8.x"},{"key":"lastsuccessstatusupdate","value":"22 Jan 16 10:19 CET"},{"key":"status","value":"bootstrapped"}],"outputs":[{"key":"publicipv4","value":"103.56.92.13"}],"policies":[],"status":"bootstrapped","created_at":"2016-01-22 09:16:03 +0000","components":["COM1302247294971805696"]}

**Comment by vijaykanthm28** [comment]
@indykish 
component json -
{"id":"COM1302247294971805696","name":"shipwreck","tosca_type":"tosca.app.java","inputs":[{"key":"domain","value":"megambox.com"},{"key":"sshkey","value":"kanth@megam.io_vs"},{"key":"provider","value":"one"},{"key":"cpu","value":"0.5"},{"key":"ram","value":"896"},{"key":"version","value":"8.x"},{"key":"lastsuccessstatusupdate","value":"22 Jan 16 10:19 CET"},{"key":"status","value":"bootstrapped"}],"outputs":[],"envs":[{"key":"port","value":"8080"},{"key":"tomcat_username","value":"megam"},{"key":"tomcat_password","value":"megam"}],"repo":{"rtype":"source","source":"github","oneclick":"","url":"https://github.com/vijaykanthm28/java-spring-petclinic.git"},"artifacts":{"artifact_type":"","content":"","requirements":[]},"related_components":[],"operations":[{"operation_type":"CI","description":"always up to date code. sweet.","properties":[{"key":"type","value":"github"},{"key":"token","value":"9fe52f81d0f206fffb746f6b273105b500f1eb16"},{"key":"username","value":"vijaykanthm28"}],"status":"notbound"}],"status":"bootstrapped","created_at":"2016-01-22 09:16:03 +0000"}

**Comment by indykish** [comment]
@vijaykanthm28  Should run now, verify it.
