### ISSUE TITLE
when stop app 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/gulp#125]
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;36;10mSTOP CARTON ASM1302335199497027584\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;37;10m==> pipeline [3]\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;32;10m  => step 0: update-status-riak action\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="  set status[COM1302335199505416192] of machine (meade.megambox.com, stopping)" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] fetch\x1b[0m (assembly, ASM1302335199497027584)" 
time="2016-01-22T16:45:40+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET --- stop box (meade.megambox.com) gulp canal COM1302335199505416192}" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] store\x1b[0m (assembly, ASM1302335199497027584)" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="  set status[COM1302335199505416192] of machine (meade.megambox.com, stopping)" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] fetch\x1b[0m (components, COM1302335199505416192)" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET   update status for machine (meade.megambox.com, stopping) gulp canal COM1302335199505416192}" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] store\x1b[0m (components, COM1302335199505416192)" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="\x1b[1;32;10m  => step 1: stop-box action\x1b[0m" 
time="2016-01-22T16:45:40+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET   stop for box (meade.megambox.com) gulp canal COM1302335199505416192}" 
ERR  705 (103.56.92.4:4150) IO error - EOF
time="2016-01-22T16:45:40+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET   meade.megambox.com --> ([java stop]) gulp canal COM1302335199505416192}" 
ERR  706 (103.56.92.4:4150) IO error - EOF
time="2016-01-22T16:45:42+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET Error: Could not find or load main class stop gulp canal COM1302335199505416192}" 
ERR  707 (103.56.92.4:4150) IO error - EOF
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[0;33;10m  => step 1: stop-box action error - exit status 1\x1b[0m" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;31;10m  => step 0: update-status-riak action\x1b[0m" 
time="2016-01-22T16:45:42+01:00" level=debug msg="  set status[COM1302335199505416192] of machine (meade.megambox.com, error)" 
time="2016-01-22T16:45:42+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET   stop for box (meade.megambox.com) failed. gulp canal COM1302335199505416192}" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] fetch\x1b[0m (assembly, ASM1302335199497027584)" 
time="2016-01-22T16:45:42+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET exit status 1 gulp canal COM1302335199505416192}" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] store\x1b[0m (assembly, ASM1302335199497027584)" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:42+01:00" level=debug msg="  set status[COM1302335199505416192] of machine (meade.megambox.com, error)" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] fetch\x1b[0m (components, COM1302335199505416192)" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] open  \x1b[0m[192.168.1.105:8087] success" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] store\x1b[0m (components, COM1302335199505416192)" 
time="2016-01-22T16:45:42+01:00" level=debug msg="\x1b[1;34;10m  > [riak] close\x1b[0m" 
time="2016-01-22T16:45:42+01:00" level=error msg="error on execute stop pipeline for box meade.megambox.com - exit status 1" 
time="2016-01-22T16:45:42+01:00" level=error msg="Unable to stop the box exit status 1"

**Comment by indykish** [comment]
@vijaykanthm28  Would like better information to fix it. 
So 1. Try stopping again manually `stop java`
2. Observe the command submitted.
3. Then try to stop using nilavu.

I see an error here.
```
ime="2016-01-22T16:45:40+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET meade.megambox.com --> ([java stop]) gulp canal COM1302335199505416192}" 
ERR 706 (103.56.92.4:4150) IO error - EOF
time="2016-01-22T16:45:42+01:00" level=debug msg="meade.megambox.com_log:{22 Jan 16 16:45 CET Error: **Could not find or load main class stop gulp canal COM1302335199505416192}"** 
ERR 707 (103.56.92.4:4150) IO error - EOF
```
