### ISSUE TITLE
CI upgrade Carton throws error

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/gulp#130]
time="2016-02-03T07:03:09+01:00" level=debug msg="\x1b[1;36;10mUPGRADE CARTON ASM1306541044795572224\x1b[0m" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4b043c]

goroutine 2829 [running]:
fmt.Fprintf(0x0, 0x0, 0xa51800, 0x19, 0xc8205c75d8, 0x1, 0x1, 0x2, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:189 +0xac
github.com/megamsys/gulp/carton.(*Upgradeable).opsBuild(0xc820436300, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/upgrade.go:106 +0x166
github.com/megamsys/gulp/carton.(*Upgradeable).(github.com/megamsys/gulp/carton.opsBuild)-fm(0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/upgrade.go:41 +0x2e
github.com/megamsys/gulp/upgrade.run(0x0, 0x0, 0xc8204e50c0, 0x12, 0xc8204e4780, 0x1, 0x4, 0x7f280447d1a8, 0xc8204e5040, 0x0, ...)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/upgrade/operation.go:143 +0x45c
github.com/megamsys/gulp/upgrade.Run(0x0, 0x0, 0xc8204e50c0, 0x12, 0xc8204e4780, 0x1, 0x4, 0x7f280447d1a8, 0xc8204e5040, 0x0, ...)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/upgrade/operation.go:129 +0x58
github.com/megamsys/gulp/carton.(*Upgradeable).operateBox(0xc8204e4fc0, 0x7f280447d1a8, 0xc8204e5040, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/upgrade.go:85 +0x289
github.com/megamsys/gulp/carton.(*Upgradeable).Upgrade(0xc8204e4fc0, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/upgrade.go:62 +0x672
github.com/megamsys/gulp/carton.(*Carton).Upgrade(0xc8204e0100, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/carton.go:101 +0x10a
github.com/megamsys/gulp/carton.UpgradeProcess.Process(0xc8204e4100, 0x16, 0xc8204e0100, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/megd_process.go:119 +0x2d
github.com/megamsys/gulp/carton.(*UpgradeProcess).Process(0xc8205f40a0, 0xc8204e0100, 0x0, 0x0)
	<autogenerated>:13 +0xae
github.com/megamsys/gulp/carton.(*ReqOperator).Accept(0xc8205c7f48, 0xc8205c7f18, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/carton/req_operator.go:42 +0x170
github.com/megamsys/gulp/subd/gulpd.(*Handler).serveNSQ(0xc82012c200, 0xc82014a050, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/subd/gulpd/handler.go:41 +0x190
created by github.com/megamsys/gulp/subd/gulpd.(*Service).processNSQ
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/subd/gulpd/service.go:92 +0xc8

goroutine 1 [chan receive, 21 minutes]:
github.com/megamsys/gulp/cmd/gulpd/run.(*Start).Run(0xc82000ef00, 0xc82000afa0, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/cmd/gulpd/run/command.go:81 +0x675
github.com/megamsys/libgo/cmd.(*Manager).Run(0xc8200f33f0, 0x0, 0x0, 0x0)
	/home/megam/.go/src/github.com/megamsys/libgo/cmd/cmd.go:184 +0x1ed1
main.main()
	/home/megam/code/workspace/go/src/github.com/megamsys/gulp/cmd/gulpd/main.go:52 +0xba

**Comment by indykish** [comment]
@vijaykanthm28  Check the line 106 in your binary, as its not in the upstream.
