### ISSUE TITLE
To find a ip private or public using following conditions

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/gulp#134]
static VALUE
addrinfo_ipv4_private_p(VALUE self)
{
    uint32_t a;
    if (!extract_in_addr(self, &a)) return Qfalse;
    if ((a & 0xff000000) == 0x0a000000 || /* 10.0.0.0/8 */
        (a & 0xfff00000) == 0xac100000 || /* 172.16.0.0/12 */
        (a & 0xffff0000) == 0xc0a80000)   /* 192.168.0.0/16 */
        return Qtrue;
    return Qfalse;
}

**Comment by indykish** [comment]
I suppose this is fixed. @vijaykanthm28  ?

**Comment by vijaykanthm28** [comment]
@indykish  fixed but not yet test for all images

**Comment by vijaykanthm28** [comment]
@indykish gulpd gets public ip, tested
