### ISSUE TITLE
To build gulp package the error in  download go.skia.org/infra/go/exec 

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/gulp#139]
godep: error downloading dep (go.skia.org/infra/go/exec): unrecognized import path "go.skia.org/infra/go/exec"
godep: error downloading dep (go.skia.org/infra/go/gitinfo): unrecognized import path "go.skia.org/infra/go/gitinfo"
godep: error downloading dep (go.skia.org/infra/go/tiling): unrecognized import path "go.skia.org/infra/go/tiling"
godep: error downloading dep (go.skia.org/infra/go/util): unrecognized import path "go.skia.org/infra/go/util"
godep: error downloading dep (go.skia.org/infra/go/vcsinfo): unrecognized import path "go.skia.org/infra/go/vcsinfo"
godep: Error downloading some deps. Aborting restore and check.

**Comment by indykish** [comment]
@ranjithamca  Is this still a bug ?
