### ISSUE TITLE
before chef-solo run notify user via log, that application is being deploy

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/gulp#145]
6 Mar 16 11:08 IST --- deploy box (plaits.megambox.com, image:megam)
16 Mar 16 05:40 UTC --- torr (/var/lib/megam/gulp/0.96.tar.gz)
16 Mar 16 05:46 UTC [32m- execute start nodejs[0m
16 Mar 16 05:46 UTC [37m+#[0m
16 Mar 16 05:46 UTC [37m+# Licensed under the Apache License, Version 2.0 (the "License");[0m
16 Mar 16 05:46 UTC [37m+#[0m
16 Mar 16 05:46 UTC [37m+#[0m
16 Mar 16 05:46 UTC (skipped due to action :nothing)
16 Mar 16 05:46 UTC [37m+# Unless required by applicable law or agreed to in writing, software[0m
16 Mar 16 05:46 UTC [37m+# Copyright 2012, Riot Games[0m
16 Mar 16 05:46 UTC [37m@@ -1 +1,67 @@[0m
16 Mar 16 05:46 UTC * template[/etc/chef/ohai_plugins/nginx.rb] action create
16 Mar 16 05:46 UTC [37m--- /etc/chef/ohai_plugins/nginx.rb	2016-03-16 05:46:58.574087999 +0000[0m
16 Mar 16 05:46 UTC [2016-03-16T05:46:58+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] updated file contents /etc/chef/ohai_plugins/nginx.rb

**Comment by indykish** [comment]
@ranjithamca  Along with the events fix, add this one in.

**Comment by vijaykanthm28** [comment]
we have to fix it on RC
