### ISSUE TITLE
Mirror issue 1254

### ISSUE THREAD

**Issue by indykish** [megamsys/gulp#175]
https://gitlab.com/megamsys/nilavu/issues/1254

**Comment by rathishvbr** [comment]
assemblies: [{:status=>"launching", :state=>"launched", :tosca_type=>"vertice.torpedo.centos", :inputs=>[{"key"=>"domain", "value"=>"megambox.com"}, {"key"=>"keypairoption", "value"=>"3"}, {"key"=>"root_password", "value"=>"bWVnYW0="}, {"key"=>"sshkey", "value"=>""}, {"key"=>"provider", "value"=>"one"}, {"key"=>"cpu", "value"=>"2 Cores"}, {"key"=>"ram", "value"=>"2 GB"}, {"key"=>"hdd", "value"=>"36 GB"}, {"key"=>"version", "value"=>"7.1"}, {"key"=>"region", "value"=>"chennai"}, {"key"=>"resource", "value"=>"c1.medium"}, {"key"=>"storage_hddtype", "value"=>"HDD"}, {"key"=>"ipv4private", "value"=>"true"}, {"key"=>"ipv4public", "value"=>"false"}, {"key"=>"ipv6private", "value"=>"false"}, {"key"=>"ipv6public", "value"=>"false"}, {"key"=>"bitnami_password", "value"=>""}, {"key"=>"bitnami_username", "value"=>""}], :id=>"", :name=>"autumn-waterfall-720", :components=>[], :outputs=>[], :policies=>[]}]


Nilavu log
