### ISSUE TITLE
localhost is not reachable

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/gulp#98]
Needs to change the conf file, by replacing localhost with loopback ip(127.0.0.1)

**Comment by thomasalrin** [comment]
Error conf : 
[meta]
    debug = true
    hostname = "localhost"

Working conf : 
  [meta]
    debug = true
    hostname = "127.0.0.1"

**Comment by indykish** [comment]
Ok, `hostname` is removed from `[meta]` section
